media:
  input: static/media
  output: /media

content:
  - name: works
    label: 'Works'
    type: collection
    view:
      fields: [title, image, tags, has_model, date]
      primary: title
      sort: [date, title, tags, has_model]
      default:
        search: ''
        sort: date
        order: desc
    path: 'src/lib/works'
    fields:
      - name: title
        label: 'Title'
        type: string
        required: true
      - name: image
        label: 'Image'
        type: image
        required: true
      - name: tags
        label: Tags
        type: select
        list:
          min: 1
          max: 4
        options:
          values: [3D, Print, Sculpture, Paint, Digital, Extra, Illustration, Mixed Media]
      - name: has_model
        label: '3D Model'
        type: boolean
        default: false
      - name: model_format
        label: 'Model Format'
        type: select
        options:
          values: [glb, gltf, splat, ply]
      - name: model_file
        label: 'Model Filename'
        type: string
        pattern:
          regex: '^.*\.(glb|splat|gltf|ply)$'
          message: 'Must be a .glb, .gltf, .splat or .ply file in the models directory'
      - name: date_text
        label: Date
        type: string
      - name: description
        label: 'Description'
        type: rich-text
        options:
          format: html
