media:
  input: static/media  # Shared media folder used by both Pages CMS and SvelteKit
  output: /media

content:
  - name: works
    label: "Works"
    type: collection
    view:
      fields: [ title, image ]
      primary: title
      sort: [ date, title ]
      default:
        search: ''
        sort: date
        order: desc
    path: "src/lib/works"
    fields:
      - name: title
        label: "Title"
        type: string
        required: true
      - name: image
        label: "Image"
        type: image
        required: true
      - name: tags
        label: Tags
        type: select
        list:
          min: 1
          max: 4
        options:
          values: [ 3D, Print, Sculpture, Paint, Digital, Extra ]
      - name: description
        label: "Description"
        type: rich-text
      - name: Date
        type: date
        options:
          format: dd/MM/yyyy
