media:
  input: static/media  # Shared media folder used by both Pages CMS and SvelteKit
  output: /media

content:
  - name: works
    label: "Works"
    type: collection
    path: "src/lib/works"
    fields:
      - name: title
        label: "Title"
        type: string
      - name: image
        label: "Image"
        type: image
      - name: tag
        label: Tag
        type: select
        options:
          values: [ 3D, Print, Sculpture, Paint, Digital, Extra ]
      - name: description
        label: "Description"
        type: rich-text
      - name: Date
        type: date
        options:
          format: dd/MM/yyyy
